### ISSUE TITLE
zipfile error

### ISSUE THREAD

**Issue by Emilevandelouw** [jakeee51/gomaps#1]
I receive an error: zipfile.BadZipFile: File is not a zip file.
can you please help me.

C:\Users\Emile\PycharmProjects\google\venv\Scripts\python.exe C:/Users/Emile/PycharmProjects/google/test1.py
[W:pyppeteer.chromium_downloader] Start patched secure https Chromium download from URL:
https://storage.googleapis.com/chromium-browser-snapshots/Win/800229/chrome-win.zip
Download may take a few minutes.
100%|██████████| 214/214 [00:00<00:00, 71355.52it/s]
[W:pyppeteer.chromium_downloader] 
chromium download done.
Traceback (most recent call last):
  File "C:/Users/Emile/PycharmProjects/google/test1.py", line 7, in <module>
    values = results[0].get_values()
  File "C:\Users\Emile\PycharmProjects\google\venv\lib\site-packages\gomaps\gmapss.py", line 178, in get_values
    self.__set_attrs(self.oq)
  File "C:\Users\Emile\PycharmProjects\google\venv\lib\site-packages\gomaps\gmapss.py", line 111, in __set_attrs
    resp = self.__sesh.get(self.__sq + quote_plus(query)); resp.html.render()
  File "C:\Users\Emile\PycharmProjects\google\venv\lib\site-packages\requests_html.py", line 586, in render
    self.browser = self.session.browser  # Automatically create a event loop and browser
  File "C:\Users\Emile\PycharmProjects\google\venv\lib\site-packages\requests_html.py", line 730, in browser
    self._browser = self.loop.run_until_complete(super().browser)
  File "C:\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Emile\PycharmProjects\google\venv\lib\site-packages\requests_html.py", line 714, in browser
    self._browser = await pyppeteer.launch(ignoreHTTPSErrors=not(self.verify), headless=True, args=self.__browser_args)
  File "C:\Users\Emile\PycharmProjects\google\venv\lib\site-packages\pyppeteer\launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\Emile\PycharmProjects\google\venv\lib\site-packages\pyppeteer\launcher.py", line 119, in __init__
    download_chromium()
  File "C:\Users\Emile\PycharmProjects\google\venv\lib\site-packages\pyppeteer\chromium_downloader.py", line 147, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
  File "C:\Users\Emile\PycharmProjects\google\venv\lib\site-packages\pyppeteer\chromium_downloader.py", line 134, in extract_zip
    with ZipFile(data) as zf:
  File "C:\Python\Python38-32\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Python\Python38-32\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Process finished with exit code 1

**Comment by jakeee51** [comment]
I wasn't able to replicate this issue on a new machine. The error seems to be derived from the **pyppeteer** package's chromium downloader. The expected output before your runtime error should look like this:

`100%|██████████| 160082578/160082578 [00:07<00:00, 22468288.86it/s]
[W:pyppeteer.chromium_downloader] 
chromium download done.
[W:pyppeteer.chromium_downloader] chromium extracted to: C:\Users\jakem\AppData\Local\pyppeteer\pyppeteer\local-chromium\800229

. . . gomaps expected output`

This response to a similar issue might aid you:
https://github.com/miyakogi/pyppeteer/issues/132#issuecomment-420858400 

Going to close for now. Feel free to contact me for further inquiry.

**Comment by jakeee51** [comment]
`test`

**Comment by pedrocastellanos** [comment]
Hello. I had the same error. I already downloaded the file manually. I tried pasting it in the path AppData\Local\pyppeteer\pyppeteer\local-chromium\800229 and it didn't work. It is still trying to download it. What can I do to avoid that?
