### ISSUE TITLE
maps_search result in error

### ISSUE THREAD

**Issue by rever96** [jakeee51/gomaps#2]
I'm trying to use this tool, I've read the doc about maps_search, and it tells nothing about my problem.

That's the code:
```
from gomaps import maps_search
results = maps_search("Ristoranti Divignano Piemonte", log=True, page_num=1)
p = results[0].get_values()
print(p)
```

running it I can see in the terminal from the log=True that it is working correctly, but instead of termitating returning the retrieved data it crash with:
```
<gomaps.GoogleMaps object; Place-Name: Ristorante Sapor di Vino>
<gomaps.GoogleMaps object; Place Not Found>
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    results = maps_search("Ristoranti Divignano Piemonte", log=True, page_num=1)
  File "/home/loris/.local/lib/python3.8/site-packages/gomaps/gmapss.py", line 293, in maps_search
    return GoogleMapsResults(q, page_num=page_num, delay=delay, log=log)
  File "/home/loris/.local/lib/python3.8/site-packages/gomaps/gmapss.py", line 219, in __init__
    result = GoogleMaps(name, session=self.__sesh)
  File "/home/loris/.local/lib/python3.8/site-packages/gomaps/gmapss.py", line 63, in __init__
    self.__set_url(url_components); del(self.__resp)
  File "/home/loris/.local/lib/python3.8/site-packages/gomaps/gmapss.py", line 100, in __set_url
    path = re.search(fr'{prefix}.+?/data.+?\\"', self.__resp.text).group()
AttributeError: 'NoneType' object has no attribute 'group'
```

it would be fine if it exit the search before throwing error

**Comment by jakeee51** [comment]
Thank you for bringing up this issue. It was throwing an error because one of the places in the results wasn't an actual place but a region. I've pushed a patch to resolve this. Please update to the latest version!
