### ISSUE TITLE
Results error

### ISSUE THREAD

**Issue by PawelKra** [jakeee51/gomaps#3]
Hey

Good tool, if You can fix it, will be great. 
Some problems occures:

>>> from gomaps import maps_search
>>> results = maps_search("Tops Diner")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.local/lib/python3.9/site-packages/gomaps/gmapss.py", line 298, in maps_search
    return GoogleMapsResults(q, page_num=page_num, delay=delay, log=log)
  File "/home/xxx/.local/lib/python3.9/site-packages/gomaps/gmapss.py", line 221, in __init__
    self._place_names = self._get_place_names(self.oq) or [self.__n_a]
  File "/home/xxx/.local/lib/python3.9/site-packages/gomaps/gmapss.py", line 255, in _get_place_names
    href.group().replace("&amp;", '&').strip('"')
AttributeError: 'NoneType' object has no attribute 'group'

Cheers

**Comment by jakeee51** [comment]
Greetings,

I was unable to reproduce this error. However, I have patched this code smell.
`pip install gomaps -U` to update to latest patch.

Best

**Comment by jakeee51** [comment]
Greetings,

I was unable to reproduce this error. However, I have patched this code smell.
Do `pip install gomaps -U` to update to latest patch.

Best
